sudo: false
cache: pip

language: python

python:
    - "3.6"
env:
    - TOXENV=manifest
    - TOXENV=docs

matrix:
    include:
        - python: "3.6"
          env: TOXENV=py36

before_install:
    - pip install codecov

install:
    - pip install tox

script:
    - tox

after_success:
    - tox -e coverage-report
    - codecov

notifications:
  slack: pybel:n2KbWKBum3musnBg3L76gGwq

deploy:
    provider: pypi
    user: cthoyt
    on:
        tags: true
        distributions: "sdist bdist_wheel"
        repo: pybel/pybel-tools
        branch: master
